name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-std, rust-src
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Test compile
        run: cargo test --release --no-run